eureka:
  client:
    serviceUrl:
      http://${spring.security.user.name}:${spring.security.user.password}@localhost:18001/eureka/
#Zipkin服务器地址
spring:
  kafka:
    bootstrap-servers: 192.168.85.6:9092
  zipkin:
    kafka:
      topic: zipkin
    sender:
      type: kafka
    service:
      name: ${spring.application.name}
  sleuth:
    sampler:
      percentage: 1.0
    enabled: true
    messaging:
      enabled: true
  redis:
    # Redis数据库索引（默认：0）
    database: 0
    host: 127.0.0.1
    jedis:
      pool:
        #最大连接数据库连接数,设 0 为没有限制
        max-active: 8
        #最大等待连接中的数量,设 0 为没有限制
        max-idle: 8
        #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
        max-wait: -1s
        #最小等待连接中的数量,设 0 为没有限制
        min-idle: 0
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1s
        min-idle: 0
      shutdown-timeout: 100ms
    password: ''
    port: 6379
    timeout: 10000ms
redis:
  connectionTimeout: 2000
  soTimeout: 2000
  maxRedirections: 5
  maxIdle: 300
  maxActive: 600
  maxWait: 1000
  testOnBorrow: true
  nodes: 127.0.0.1:6379,127.0.0.1:6380,127.0.0.1:6381,127.0.0.1:6382,127.0.0.1:6383,127.0.0.1:6384
