spring:
  profiles:
    active: @environment@
  messages:
    basename: web/resultCode
  #gzip压缩配置
  compression:
    enabled: true
    mime-types: application/json ,application/xml,text/html,text/xml,text/plain
    min-response-size: 2048 #默认就是2048 byte
  cloud:
    loadbalancer:
      retry:
        enabled: true
  security:
    user:
      name: @mall.username@
      password: @monitor.pwd@

#  boot:
#    admin:
#      url: @monitor.url@


server:
  port: 18002
  servlet:
    context-path: /



eureka:
# 实例配置类： EurekaInstanceConfigBean
  instance:

     # 设置微服务调用地址为IP优先（缺省为false）
#    perferIpAddress: true
    prefer-ip-address: true
#    instance-id: ${spring.cloud.client.ipAddress}:${spring.application.name}:${server.port}
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${server.port}
     # 心跳时间，即服务续约间隔时间（缺省为30s）
#    leaseRenewalIntervalInSeconds: 10
    lease-renewal-interval-in-seconds: 5
     # 发呆时间，即服务续约到期时间（缺省为90s）
    lease-expiration-duration-in-seconds: 30


    # 客户端配置类： EurekaClientConfigBean
  client:
    healthcheck:
      # 开启健康检查（依赖spring-boot-starter-actuator）
      enabled: true
    #从eureka服务器注册表中获取注册信息的时间间隔（s），默认为30秒
    registryFetchIntervalSeconds: 5
    #是否从服务注册中心获取可用的服务清单，默认为true
    fetch-registry: true
    #是否将自己注册到eureka服务注册中心，默认为true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@localhost:18001/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'