#Zipkin服务器地址 #默认http通信的配置方式
#spring:
#  zipkin:
#    connectTimeout: 10
#    readTimeout: 10
#    flushInterval: 2
#    baseUrl:  http://localhost:17003/
#    service:
#      name:  ${spring.application.name}
#    compression:
#      enabled: false

# zipkin kafka
spring:
  kafka:
    bootstrap-servers: 36.155.127.23:9092
  zipkin:
    kafka:
      topic: zipkin
    sender:
      type: kafka
    service:
      name: ${spring.application.name}
  sleuth:
    sampler:
      percentage: 1.0
    enabled: true
    messaging:
      enabled: true