eureka:
  instance:
    #从系统环境变量总读取host
    hostname: ${HOST}
  client:
    serviceUrl:
       defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@10.76.137.66:18001/eureka/,http://${spring.security.user.name}:${spring.security.user.password}@10.76.137.67:18001/eureka/

#Zipkin服务器地址
spring:
#  kafka:
#    bootstrap-servers: 10.76.137.82:9092
#  zipkin:
#    kafka:
#      topic: zipkin
#    sender:
#      type: kafka
#    service:
#      name: ${spring.application.name}
#  sleuth:
#    sampler:
#      percentage: 1.0
#    enabled: true
#    messaging:
#      enabled: true
